/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.Booking;
import Bean.Room;
import Bean.RoomType;
import DTO.BookingData;
import DTO.RoomTypeData;
import DTO.RoomsData;
import Logic.Billing;
import Logic.RoomBooking;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thehackermonk
 */
public class BookingForm extends javax.swing.JFrame {

    /**
     * Creates new form BookingForm
     */
    public BookingForm() {
        initComponents();
    }

    /**
     * To clear the form
     */
    public void clear() {

        DefaultComboBoxModel roomNoComboBoxModel = (DefaultComboBoxModel) roomNoComboBox.getModel();

        nameTextField.setText("");
        contactTextField.setText("");
        paymentTextField.setText("");

        roomNoComboBoxModel.removeAllElements();

    }

    public void clearCancelDialog() {

        delNameTextField.setText("");
        delContactTextField.setText("");

    }

    /**
     * to load type of rooms to combo box
     *
     * @param comboBox
     */
    public void refreshRoomTypeComboBox(DefaultComboBoxModel comboBox) {

        RoomTypeData roomTypeData = new RoomTypeData();

        ArrayList<RoomType> roomTypeList = roomTypeData.getAllRoomTypeDetails();
        Iterator<RoomType> roomTypeListIterator = roomTypeList.iterator();

        comboBox.removeAllElements();

        while (roomTypeListIterator.hasNext()) {

            RoomType roomType = roomTypeListIterator.next();

            comboBox.addElement(roomType.getType());

        }

    }

    /**
     * to load room nos to combo box
     *
     * @param comboBox
     * @param type
     */
    public void refreshRoomNoComboBox(DefaultComboBoxModel comboBox, String type) {

        RoomsData roomsData = new RoomsData();

        ArrayList<Room> roomList = roomsData.getRoomNoOfType(type);
        Iterator<Room> roomListIterator = roomList.iterator();

        comboBox.removeAllElements();

        while (roomListIterator.hasNext()) {

            Room room = roomListIterator.next();

            comboBox.addElement(room.getRoomNo());

        }

    }

    /**
     * Get all booking to the bookings Table
     *
     * @param bookingTable
     */
    public void refreshBookingTable(DefaultTableModel bookingTable) {

        BookingData bookingData = new BookingData();

        while (bookingTable.getRowCount() > 0) {
            bookingTable.removeRow(0);
        }

        ArrayList<Booking> bookingList = bookingData.getAllBookingDetails();
        Iterator<Booking> bookingListIterator = bookingList.iterator();

        while (bookingListIterator.hasNext()) {

            Booking booking = bookingListIterator.next();

            bookingTable.addRow(new Object[]{"ALaCarte#" + booking.getBookingID(), booking.getName(), booking.getContact(), booking.getRoomNo(), booking.getFromDate(), booking.getToDate()});

        }

    }

    /**
     * Get the search results to the bookings table
     *
     * @param bookingTable
     * @param name
     * @param contact
     */
    public void searchBookings(DefaultTableModel bookingTable, String name, String contact) {

        BookingData bookingData = new BookingData();

        ArrayList<Booking> bookingList = bookingData.searchBookings(name, contact);
        Iterator<Booking> bookingListIterator = bookingList.iterator();

        while (bookingTable.getRowCount() > 0) {
            bookingTable.removeRow(0);
        }

        while (bookingListIterator.hasNext()) {

            Booking booking = bookingListIterator.next();

            bookingTable.addRow(new Object[]{"ALaCarte#" + booking.getBookingID(), booking.getName(), booking.getContact(), booking.getRoomNo(), booking.getFromDate(), booking.getToDate()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelBookingDialog = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        delNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        delContactTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        delBookingsTable = new javax.swing.JTable();
        delDeleteButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        roomTypeComboBox = new javax.swing.JComboBox<>();
        roomNoComboBox = new javax.swing.JComboBox<>();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        toDateChooser = new com.toedter.calendar.JDateChooser();
        paymentTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bookRoomButton = new javax.swing.JButton();
        checkAvailabilityButton = new javax.swing.JButton();
        cancelBookingButton = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Name");

        delNameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        delNameTextField.setText("jTextField2");
        delNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                delNameTextFieldKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Contact");

        delContactTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        delContactTextField.setText("jTextField3");
        delContactTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                delContactTextFieldKeyReleased(evt);
            }
        });

        delBookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Name", "Contact", "Room No", "From", "To"
            }
        ));
        jScrollPane1.setViewportView(delBookingsTable);

        delDeleteButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        delDeleteButton.setText("DELETE BOOKING");
        delDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancelBookingDialogLayout = new javax.swing.GroupLayout(cancelBookingDialog.getContentPane());
        cancelBookingDialog.getContentPane().setLayout(cancelBookingDialogLayout);
        cancelBookingDialogLayout.setHorizontalGroup(
            cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBookingDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delDeleteButton)
                .addGap(555, 555, 555))
            .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delContactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        cancelBookingDialogLayout.setVerticalGroup(
            cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelBookingDialogLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(cancelBookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(delNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(delContactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(delDeleteButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        nameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameTextField.setText("jTextField1");

        contactTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        contactTextField.setText("jTextField2");

        roomTypeComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        roomNoComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomNoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomNoComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roomNoComboBoxFocusGained(evt);
            }
        });

        fromDateChooser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        toDateChooser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        paymentTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        paymentTextField.setText("jTextField3");
        paymentTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentTextFieldFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Contact No.");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Room Type");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Room No");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("From Date");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("To Date");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Payment");

        jButton1.setText("X");

        bookRoomButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bookRoomButton.setText("BOOK ROOM");
        bookRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomButtonActionPerformed(evt);
            }
        });

        checkAvailabilityButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        checkAvailabilityButton.setText("CHECK AVAILABILITY");
        checkAvailabilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAvailabilityButtonActionPerformed(evt);
            }
        });

        cancelBookingButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancelBookingButton.setText("CANCEL BOOKING");
        cancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(568, 568, 568)
                                .addComponent(checkAvailabilityButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(504, 504, 504)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameTextField)
                                            .addComponent(contactTextField)
                                            .addComponent(roomTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(roomNoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fromDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(toDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(bookRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cancelBookingButton)))))
                        .addGap(0, 449, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(checkAvailabilityButton)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookRoomButton)
                    .addComponent(cancelBookingButton))
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        DefaultComboBoxModel roomTypeComboBoxModel = (DefaultComboBoxModel) roomTypeComboBox.getModel();

        clear();
        refreshRoomTypeComboBox(roomTypeComboBoxModel);
        paymentTextField.setEditable(false);
        bookRoomButton.setEnabled(false);
        nameTextField.requestFocus();

        fromDateChooser.setMinSelectableDate(Calendar.getInstance().getTime());
        toDateChooser.setMinSelectableDate(Calendar.getInstance().getTime());

    }//GEN-LAST:event_formWindowGainedFocus

    private void roomNoComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomNoComboBoxFocusGained

        DefaultComboBoxModel roomNoComboBoxModel = (DefaultComboBoxModel) roomNoComboBox.getModel();

        String type = roomTypeComboBox.getSelectedItem().toString();

        refreshRoomNoComboBox(roomNoComboBoxModel, type);

    }//GEN-LAST:event_roomNoComboBoxFocusGained

    private void paymentTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentTextFieldFocusGained

        Billing billing = new Billing();

        String type;
        Date fromDate, toDate;
        int percentage = 20;
        float payment;

        type = roomTypeComboBox.getSelectedItem().toString();
        fromDate = fromDateChooser.getDate();
        toDate = toDateChooser.getDate();

        payment = billing.calculateAdvancePayment(type, fromDate, toDate, percentage);

        paymentTextField.setText(payment + "");

    }//GEN-LAST:event_paymentTextFieldFocusGained

    private void bookRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomButtonActionPerformed

        Booking booking = new Booking();
        BookingData bookingData = new BookingData();

        int bookingID;

        booking.setName(nameTextField.getText());
        booking.setContact(contactTextField.getText());
        booking.setRoomNo(Integer.parseInt(roomNoComboBox.getSelectedItem().toString()));
        booking.setFromDate(fromDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        booking.setToDate(toDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        booking.setPayment(Float.parseFloat(paymentTextField.getText()));

        if (bookingData.bookRoom(booking)) {

            JOptionPane.showMessageDialog(null, "Your booking was successful!");

        }
        bookingID = bookingData.getLastBookingID();
        JOptionPane.showMessageDialog(null, "Your booking number is ALaCarte#" + bookingID);

    }//GEN-LAST:event_bookRoomButtonActionPerformed

    private void checkAvailabilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAvailabilityButtonActionPerformed

        RoomBooking room = new RoomBooking();

        if (roomNoComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Please select room no!");
        } else if (fromDateChooser.getDate() == null || toDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please select both dates!");
        } else {

            int roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
            LocalDate fromDate = fromDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate toDate = toDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (room.checkAvailability(roomNo, fromDate, toDate)) {
                bookRoomButton.setEnabled(true);
            } else {
                bookRoomButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_checkAvailabilityButtonActionPerformed

    private void cancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingButtonActionPerformed

        DefaultTableModel bookingTableModel = (DefaultTableModel) delBookingsTable.getModel();

        clearCancelDialog();
        refreshBookingTable(bookingTableModel);

        cancelBookingDialog.setSize(1250, 650);
        cancelBookingDialog.show();

    }//GEN-LAST:event_cancelBookingButtonActionPerformed

    private void delNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delNameTextFieldKeyReleased

        DefaultTableModel tableModel = (DefaultTableModel) delBookingsTable.getModel();
        String name, contact;

        if (delNameTextField.getText() == null) {
            name = "";
        } else {
            name = delNameTextField.getText();
        }

        if (delContactTextField.getText() == null) {
            contact = "";
        } else {
            contact = delContactTextField.getText();
        }

        searchBookings(tableModel, name, contact);

    }//GEN-LAST:event_delNameTextFieldKeyReleased

    private void delContactTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delContactTextFieldKeyReleased

        DefaultTableModel tableModel = (DefaultTableModel) delBookingsTable.getModel();
        String name, contact;

        if (delNameTextField.getText() == null) {
            name = "";
        } else {
            name = delNameTextField.getText();
        }

        if (delContactTextField.getText() == null) {
            contact = "";
        } else {
            contact = delContactTextField.getText();
        }

        searchBookings(tableModel, name, contact);

    }//GEN-LAST:event_delContactTextFieldKeyReleased

    private void delDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDeleteButtonActionPerformed

        BookingData bookingData = new BookingData();

        String bookingID;
        int booking, confirm;

        JOptionPane.showMessageDialog(null, "Enter booking ID like ALaCarte#1");
        bookingID = JOptionPane.showInputDialog("Enter booking ID");
        booking = Integer.parseInt(bookingID.substring(9));
        confirm = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + bookingID);

        if (confirm == 0) {
            if (bookingData.deleteBooking(booking)) {

                JOptionPane.showMessageDialog(null, bookingID + " deleted successfully!");

            }
        }

    }//GEN-LAST:event_delDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookRoomButton;
    private javax.swing.JButton cancelBookingButton;
    private javax.swing.JDialog cancelBookingDialog;
    private javax.swing.JButton checkAvailabilityButton;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTable delBookingsTable;
    private javax.swing.JTextField delContactTextField;
    private javax.swing.JButton delDeleteButton;
    private javax.swing.JTextField delNameTextField;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JComboBox<String> roomNoComboBox;
    private javax.swing.JComboBox<String> roomTypeComboBox;
    private com.toedter.calendar.JDateChooser toDateChooser;
    // End of variables declaration//GEN-END:variables
}
