/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.GuestRegister;
import DTO.GuestRegisterData;
import Logic.Billing;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author thehackermonk
 */
public class CheckOutForm extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutForm
     */
    public CheckOutForm() {
        initComponents();
    }

    /**
     * Set theme of the form
     */
    public void setTheme() {

        this.getContentPane().setBackground(new Color(246, 252, 252));

        titleLabel.setForeground(new Color(45, 58, 84));
        roomNoLabel.setForeground(new Color(45, 58, 84));
        contactLabel.setForeground(new Color(45, 58, 84));
        checkInLabel.setForeground(new Color(45, 58, 84));
        checkOutLabel.setForeground(new Color(45, 58, 84));
        bookingIDLabel.setForeground(new Color(45, 58, 84));
        totalAmountLabel.setForeground(new Color(45, 58, 84));
        amountPayableLabel.setForeground(new Color(45, 58, 84));

    }

    /**
     * To clear all the text fields
     */
    public void clear() {

        nameTextField.setText("");
        contactNoTextField.setText("");
        checkInDateTextField.setText("");
        amountPayableTextField.setText("");
        bookingIDTextField.setText("");
        totalAmountTextField.setText("");

    }

    /**
     * To get all the rooms where guests are currently staying
     */
    public void refreshRoomNoComboBox() {

        GuestRegisterData checkOutData = new GuestRegisterData();

        DefaultComboBoxModel roomNoComboBoxModel = (DefaultComboBoxModel) roomNoComboBox.getModel();

        ArrayList<GuestRegister> guestRegisterList;
        Iterator<GuestRegister> guestRegisterListIterator;

        roomNoComboBoxModel.removeAllElements();

        guestRegisterList = checkOutData.getOccupiedRooms();
        guestRegisterListIterator = guestRegisterList.iterator();

        while (guestRegisterListIterator.hasNext()) {

            GuestRegister guestRegister = guestRegisterListIterator.next();

            roomNoComboBoxModel.addElement(guestRegister.getRoomNo());

        }

    }

    /**
     * To calculate the total amount payable
     */
    public void payableBill() {

        Billing billing = new Billing();
        int roomNo, bookingID = 0;
        Date checkInDate, checkOutDate;

        try {

            roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
            checkInDate = new java.sql.Date(new SimpleDateFormat("yyyy-mm-dd").parse(checkInDateTextField.getText()).getTime());
            checkOutDate = new java.sql.Date(checkOutDateChooser.getDate().getTime());

            if (!(bookingIDTextField.getText().equals(""))) {
                if (!(bookingIDTextField.getText().substring(9).equals(""))) {
                    bookingID = Integer.parseInt(bookingIDTextField.getText().substring(9));
                }
            }

            totalAmountTextField.setText(billing.getTotalAmount(roomNo, checkInDate, checkOutDate) + "");
            amountPayableTextField.setText(billing.getPayableAmount(roomNo, bookingID, checkInDate, checkOutDate) + "");

        } catch (ParseException ex) {
            Logger.getLogger(CheckOutForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomNoLabel = new javax.swing.JLabel();
        roomNoComboBox = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        contactNoTextField = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        checkInDateTextField = new javax.swing.JTextField();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        checkOutDateChooser = new com.toedter.calendar.JDateChooser();
        amountPayableTextField = new javax.swing.JTextField();
        amountPayableLabel = new javax.swing.JLabel();
        checkOutButton = new javax.swing.JButton();
        bookingIDTextField = new javax.swing.JTextField();
        bookingIDLabel = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        totalAmountLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        roomNoLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        roomNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        roomNoLabel.setText("Room No");

        roomNoComboBox.setBackground(new java.awt.Color(246, 252, 252));
        roomNoComboBox.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        roomNoComboBox.setForeground(new java.awt.Color(45, 58, 84));
        roomNoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomNoComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                roomNoComboBoxFocusLost(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Name");

        nameTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        nameTextField.setText("jTextField1");

        contactNoTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        contactNoTextField.setText("jTextField2");

        contactLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        contactLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        contactLabel.setText("Contact No");

        checkInDateTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        checkInDateTextField.setText("jTextField3");

        checkInLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        checkInLabel.setText("Check In Date");

        checkOutLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        checkOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        checkOutLabel.setText("Check Out Date");

        checkOutDateChooser.setBackground(new java.awt.Color(246, 252, 252));
        checkOutDateChooser.setForeground(new java.awt.Color(45, 58, 84));
        checkOutDateChooser.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        amountPayableTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        amountPayableTextField.setText("jTextField4");
        amountPayableTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountPayableTextFieldFocusGained(evt);
            }
        });

        amountPayableLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        amountPayableLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        amountPayableLabel.setText("Amount Payable");

        checkOutButton.setBackground(new java.awt.Color(108, 160, 209));
        checkOutButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        checkOutButton.setForeground(new java.awt.Color(255, 255, 255));
        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        bookingIDTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        bookingIDTextField.setText("jTextField1");
        bookingIDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookingIDTextFieldFocusGained(evt);
            }
        });

        bookingIDLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        bookingIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bookingIDLabel.setText("Booking ID");

        totalAmountTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        totalAmountTextField.setText("jTextField1");
        totalAmountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalAmountTextFieldFocusGained(evt);
            }
        });

        totalAmountLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        totalAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalAmountLabel.setText("Total Amount");

        closeButton.setBackground(new java.awt.Color(255, 0, 0));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titleLabel.setText("Check Out");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Hotel.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addComponent(titleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkOutLabel)
                            .addComponent(roomNoLabel)
                            .addComponent(nameLabel)
                            .addComponent(contactLabel)
                            .addComponent(checkInLabel)
                            .addComponent(bookingIDLabel)
                            .addComponent(totalAmountLabel)
                            .addComponent(amountPayableLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountPayableTextField)
                            .addComponent(totalAmountTextField)
                            .addComponent(bookingIDTextField)
                            .addComponent(contactNoTextField)
                            .addComponent(nameTextField)
                            .addComponent(roomNoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkOutDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkInDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomNoLabel)
                            .addComponent(roomNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkInDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkInLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkOutLabel)
                            .addComponent(checkOutDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingIDLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalAmountLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountPayableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountPayableLabel))
                        .addGap(38, 38, 38)
                        .addComponent(checkOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(titleLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                .addComponent(jLabel8)))))
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        setTheme();

        clear();
        refreshRoomNoComboBox();

        amountPayableTextField.setEditable(false);
        totalAmountTextField.setEditable(false);
        
        roomNoComboBox.requestFocus();

    }//GEN-LAST:event_formWindowGainedFocus

    private void roomNoComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomNoComboBoxFocusLost

        GuestRegister guestRegister;
        GuestRegisterData guestRegisterData = new GuestRegisterData();

        int roomNo;
        Date date = new Date();

        roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
        guestRegister = guestRegisterData.getGuestDetails(roomNo);

        nameTextField.setText(guestRegister.getName());
        contactNoTextField.setText(guestRegister.getTelephoneNo());
        checkInDateTextField.setText(guestRegister.getCheckInDate() + "");
        checkOutDateChooser.setDate(date);

    }//GEN-LAST:event_roomNoComboBoxFocusLost

    private void bookingIDTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookingIDTextFieldFocusGained

        bookingIDTextField.setText("ALaCarte#");

    }//GEN-LAST:event_bookingIDTextFieldFocusGained

    private void amountPayableTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountPayableTextFieldFocusGained

        payableBill();

    }//GEN-LAST:event_amountPayableTextFieldFocusGained

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed

        GuestRegisterData guestRegisterData = new GuestRegisterData();

        int roomNo;
        java.sql.Date checkInDate, checkOutDate;

        try {

            roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
            checkInDate = new java.sql.Date(new SimpleDateFormat("yyyy-mm-dd").parse(checkInDateTextField.getText()).getTime());
            checkOutDate = new java.sql.Date(checkOutDateChooser.getDate().getTime());

            if (guestRegisterData.checkOut(roomNo, checkInDate, checkOutDate)) {
                JOptionPane.showMessageDialog(null, "Check out complete.");
            }

        } catch (HeadlessException | NumberFormatException | ParseException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void totalAmountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalAmountTextFieldFocusGained

        payableBill();

    }//GEN-LAST:event_totalAmountTextFieldFocusGained

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        this.setVisible(false);
        new FrontOfficeMenu().show();

    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPayableLabel;
    private javax.swing.JTextField amountPayableTextField;
    private javax.swing.JLabel bookingIDLabel;
    private javax.swing.JTextField bookingIDTextField;
    private javax.swing.JTextField checkInDateTextField;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JButton checkOutButton;
    private com.toedter.calendar.JDateChooser checkOutDateChooser;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactNoTextField;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> roomNoComboBox;
    private javax.swing.JLabel roomNoLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JTextField totalAmountTextField;
    // End of variables declaration//GEN-END:variables
}
