/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.GuestRegister;
import DTO.GuestRegisterData;
import Logic.Billing;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author thehackermonk
 */
public class CheckOutForm extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutForm
     */
    public CheckOutForm() {
        initComponents();
    }

    /**
     * To clear all the text fields
     */
    public void clear() {

        nameTextField.setText("");
        contactNoTextField.setText("");
        checkInDateTextField.setText("");
        amountPayableTextField.setText("");
        bookingIDTextField.setText("");
        totalAmountTextField.setText("");

    }

    /**
     * To get all the rooms where guests are currently staying
     */
    public void refreshRoomNoComboBox() {

        GuestRegisterData checkOutData = new GuestRegisterData();

        DefaultComboBoxModel roomNoComboBoxModel = (DefaultComboBoxModel) roomNoComboBox.getModel();

        ArrayList<GuestRegister> guestRegisterList;
        Iterator<GuestRegister> guestRegisterListIterator;

        roomNoComboBoxModel.removeAllElements();

        guestRegisterList = checkOutData.getOccupiedRooms();
        guestRegisterListIterator = guestRegisterList.iterator();

        while (guestRegisterListIterator.hasNext()) {

            GuestRegister guestRegister = guestRegisterListIterator.next();

            roomNoComboBoxModel.addElement(guestRegister.getRoomNo());

        }

    }

    /**
     * To calculate the total amount payable
     */
    public void payableBill() {

        Billing billing = new Billing();
        int roomNo, bookingID = 0;
        Date checkInDate, checkOutDate;

        try {

            roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
            checkInDate = new java.sql.Date(new SimpleDateFormat("yyyy-mm-dd").parse(checkInDateTextField.getText()).getTime());
            checkOutDate = new java.sql.Date(checkOutDateChooser.getDate().getTime());

            if (!(bookingIDTextField.getText().equals(""))) {
                if (!(bookingIDTextField.getText().substring(9).equals(""))) {
                    bookingID = Integer.parseInt(bookingIDTextField.getText().substring(9));
                }
            }

            totalAmountTextField.setText(billing.getTotalAmount(roomNo, checkInDate, checkOutDate) + "");
            amountPayableTextField.setText(billing.getPayableAmount(roomNo, bookingID, checkInDate, checkOutDate) + "");

        } catch (ParseException ex) {
            Logger.getLogger(CheckOutForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        roomNoComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        contactNoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkInDateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkOutDateChooser = new com.toedter.calendar.JDateChooser();
        amountPayableTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkOutButton = new javax.swing.JButton();
        bookingIDTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Room No");

        roomNoComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomNoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomNoComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                roomNoComboBoxFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Name");

        nameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameTextField.setText("jTextField1");

        contactNoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        contactNoTextField.setText("jTextField2");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Contact No");

        checkInDateTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        checkInDateTextField.setText("jTextField3");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Check In Date");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Check Out Date");

        checkOutDateChooser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        amountPayableTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        amountPayableTextField.setText("jTextField4");
        amountPayableTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountPayableTextFieldFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Amount Payable");

        checkOutButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        bookingIDTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bookingIDTextField.setText("jTextField1");
        bookingIDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookingIDTextFieldFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Booking ID");

        totalAmountTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        totalAmountTextField.setText("jTextField1");
        totalAmountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalAmountTextFieldFocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Total Amount");

        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountPayableTextField)
                    .addComponent(totalAmountTextField)
                    .addComponent(bookingIDTextField)
                    .addComponent(contactNoTextField)
                    .addComponent(nameTextField)
                    .addComponent(roomNoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkOutDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(checkInDateTextField))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(checkOutDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountPayableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addComponent(checkOutButton)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        clear();
        refreshRoomNoComboBox();

        amountPayableTextField.setEditable(false);
        totalAmountTextField.setEditable(false);

    }//GEN-LAST:event_formWindowGainedFocus

    private void roomNoComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomNoComboBoxFocusLost

        GuestRegister guestRegister;
        GuestRegisterData guestRegisterData = new GuestRegisterData();

        int roomNo;
        Date date = new Date();

        roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
        guestRegister = guestRegisterData.getGuestDetails(roomNo);

        nameTextField.setText(guestRegister.getName());
        contactNoTextField.setText(guestRegister.getTelephoneNo());
        checkInDateTextField.setText(guestRegister.getCheckInDate() + "");
        checkOutDateChooser.setDate(date);

    }//GEN-LAST:event_roomNoComboBoxFocusLost

    private void bookingIDTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookingIDTextFieldFocusGained

        bookingIDTextField.setText("ALaCarte#");

    }//GEN-LAST:event_bookingIDTextFieldFocusGained

    private void amountPayableTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountPayableTextFieldFocusGained

        payableBill();

    }//GEN-LAST:event_amountPayableTextFieldFocusGained

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed

        GuestRegisterData guestRegisterData = new GuestRegisterData();

        int roomNo;
        java.sql.Date checkInDate, checkOutDate;

        try {

            roomNo = Integer.parseInt(roomNoComboBox.getSelectedItem().toString());
            checkInDate = new java.sql.Date(new SimpleDateFormat("yyyy-mm-dd").parse(checkInDateTextField.getText()).getTime());
            checkOutDate = new java.sql.Date(checkOutDateChooser.getDate().getTime());

            if (guestRegisterData.checkOut(roomNo, checkInDate, checkOutDate)) {
                JOptionPane.showMessageDialog(null, "Check out complete.");
            }

        } catch (HeadlessException | NumberFormatException | ParseException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void totalAmountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalAmountTextFieldFocusGained

        payableBill();

    }//GEN-LAST:event_totalAmountTextFieldFocusGained

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.setVisible(false);
        new FrontOfficeMenu().show();
        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountPayableTextField;
    private javax.swing.JTextField bookingIDTextField;
    private javax.swing.JTextField checkInDateTextField;
    private javax.swing.JButton checkOutButton;
    private com.toedter.calendar.JDateChooser checkOutDateChooser;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField contactNoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> roomNoComboBox;
    private javax.swing.JTextField totalAmountTextField;
    // End of variables declaration//GEN-END:variables
}
