/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.Food;
import DTO.FoodData;
import Logic.Sort;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author thehackermonk
 */
public class FoodForm extends javax.swing.JFrame {

    /**
     * Creates new form FoodForm
     */
    public FoodForm() {
        initComponents();
    }

    /**
     * Set theme of the form
     */
    public void setTheme() {

        this.getContentPane().setBackground(new Color(246, 252, 252));
        addFoodDialog.getContentPane().setBackground(new Color(246, 252, 252));
        modifyFoodDialog.getContentPane().setBackground(new Color(246, 252, 252));
        removeFoodDialog.getContentPane().setBackground(new Color(246, 252, 252));

        titleLabel.setForeground(new Color(45, 58, 84));
        addNDBLabel.setForeground(new Color(45, 58, 84));
        addNameLabel.setForeground(new Color(45, 58, 84));
        addDescriptionLabel.setForeground(new Color(45, 58, 84));
        addPriceLabel.setForeground(new Color(45, 58, 84));
        modifyFoodLabel.setForeground(new Color(45, 58, 84));
        modifyDescriptionLabel.setForeground(new Color(45, 58, 84));
        modifyPriceLabel.setForeground(new Color(45, 58, 84));
        removeNameLabel.setForeground(new Color(45, 58, 84));
        removeDecriptionLabel.setForeground(new Color(45, 58, 84));

        foodTable.getTableHeader().setDefaultRenderer(new DefaultTableCellHeaderRenderer() {

            @Override
            public void setOpaque(boolean isOpaque) {
                super.setOpaque(true); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void setBackground(Color c) {
                super.setBackground(new Color(45, 58, 84)); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void setForeground(Color c) {
                super.setForeground(new Color(255, 255, 255)); //To change body of generated methods, choose Tools | Templates.
            }

        });

    }

    /**
     * Clear the fields in add food dialog
     */
    public void clearAddFoodDialog() {

        addNDBNoTextField.setText("");
        addNameTextField.setText("");
        addDescriptionTextArea.setText("");
        addPriceTextField.setText("");

    }

    /**
     * Clear the fields in modify food dialog
     */
    public void clearModifyDialog() {

        modifyFoodNameTextField.setText("");
        modifyFoodDescriptionTextArea.setText("");
        modifyFoodPriceTextField.setText("");

    }

    /**
     * Refresh the values of room table
     *
     * @param table
     */
    public void refreshFoodTable(DefaultTableModel table) {

        FoodData foodData = new FoodData();

        ArrayList<Food> foodList = foodData.getAllFoodDetails();
        Iterator<Food> foodListIterator = foodList.iterator();

        while (table.getRowCount() > 0) {
            table.removeRow(0);
        }

        while (foodListIterator.hasNext()) {

            Food food = foodListIterator.next();
            table.addRow(new Object[]{food.getName(), food.getDescription(), food.getPrice()});

        }

    }

    /**
     * Refresh the values of food name combo box
     *
     * @param comboBox
     */
    public void refreshFoodNameCombo(DefaultComboBoxModel comboBox) {

        FoodData foodData = new FoodData();

        ArrayList<Food> foodList = foodData.getAllFoodDetails();
        Iterator<Food> foodListIterator = foodList.iterator();

        comboBox.removeAllElements();

        while (foodListIterator.hasNext()) {

            Food food = foodListIterator.next();
            comboBox.addElement(food.getName());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFoodDialog = new javax.swing.JDialog();
        addNDBLabel = new javax.swing.JLabel();
        addNDBNoTextField = new javax.swing.JTextField();
        addNameTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addDescriptionTextArea = new javax.swing.JTextArea();
        addPriceTextField = new javax.swing.JTextField();
        addNameLabel = new javax.swing.JLabel();
        addDescriptionLabel = new javax.swing.JLabel();
        addPriceLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        modifyFoodDialog = new javax.swing.JDialog();
        modifyFoodNameCombo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        modifyFoodDescriptionTextArea = new javax.swing.JTextArea();
        modifyFoodNameTextField = new javax.swing.JTextField();
        modifyFoodLabel = new javax.swing.JLabel();
        modifyDescriptionLabel = new javax.swing.JLabel();
        modifyFoodPriceTextField = new javax.swing.JTextField();
        modifyPriceLabel = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        modifyResetButton = new javax.swing.JButton();
        removeFoodDialog = new javax.swing.JDialog();
        removeNameLabel = new javax.swing.JLabel();
        removeFoodNameComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        removeFoodDescriptionTextArea = new javax.swing.JTextArea();
        removeDecriptionLabel = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        addFoodButton = new javax.swing.JButton();
        editFoodButton = new javax.swing.JButton();
        removeFoodButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        addNDBLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addNDBLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addNDBLabel.setText("NDB No.");

        addNDBNoTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addNDBNoTextField.setText("jTextField1");
        addNDBNoTextField.setDisabledTextColor(new java.awt.Color(108, 160, 209));

        addNameTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addNameTextField.setText("jTextField2");
        addNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addNameTextFieldKeyReleased(evt);
            }
        });

        addDescriptionTextArea.setColumns(20);
        addDescriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addDescriptionTextArea.setLineWrap(true);
        addDescriptionTextArea.setRows(5);
        addDescriptionTextArea.setWrapStyleWord(true);
        addDescriptionTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addDescriptionTextAreaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(addDescriptionTextArea);

        addPriceTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addPriceTextField.setText("jTextField3");

        addNameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addNameLabel.setText("Name");

        addDescriptionLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addDescriptionLabel.setText("Description");

        addPriceLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addPriceLabel.setText("Price");

        addButton.setBackground(new java.awt.Color(108, 160, 209));
        addButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD FOOD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addFoodDialogLayout = new javax.swing.GroupLayout(addFoodDialog.getContentPane());
        addFoodDialog.getContentPane().setLayout(addFoodDialogLayout);
        addFoodDialogLayout.setHorizontalGroup(
            addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFoodDialogLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addFoodDialogLayout.createSequentialGroup()
                            .addComponent(addPriceLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addFoodDialogLayout.createSequentialGroup()
                            .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addNDBLabel)
                                .addComponent(addNameLabel)
                                .addComponent(addDescriptionLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(addNameTextField)
                                .addComponent(addNDBNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFoodDialogLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(288, 288, 288))
        );
        addFoodDialogLayout.setVerticalGroup(
            addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFoodDialogLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNDBLabel)
                    .addComponent(addNDBNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNameLabel))
                .addGap(18, 18, 18)
                .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDescriptionLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPriceLabel))
                .addGap(29, 29, 29)
                .addComponent(addButton)
                .addGap(100, 100, 100))
        );

        modifyFoodNameCombo.setBackground(new java.awt.Color(246, 252, 252));
        modifyFoodNameCombo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyFoodNameCombo.setForeground(new java.awt.Color(45, 58, 84));
        modifyFoodNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modifyFoodNameCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modifyFoodNameComboFocusLost(evt);
            }
        });

        modifyFoodDescriptionTextArea.setColumns(20);
        modifyFoodDescriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyFoodDescriptionTextArea.setLineWrap(true);
        modifyFoodDescriptionTextArea.setRows(5);
        modifyFoodDescriptionTextArea.setWrapStyleWord(true);
        modifyFoodDescriptionTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modifyFoodDescriptionTextAreaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(modifyFoodDescriptionTextArea);

        modifyFoodNameTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyFoodNameTextField.setText("jTextField1");
        modifyFoodNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modifyFoodNameTextFieldKeyReleased(evt);
            }
        });

        modifyFoodLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyFoodLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        modifyFoodLabel.setText("Food");

        modifyDescriptionLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        modifyDescriptionLabel.setText("Description");

        modifyFoodPriceTextField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyFoodPriceTextField.setText("jTextField2");

        modifyPriceLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        modifyPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        modifyPriceLabel.setText("Price");

        modifyButton.setBackground(new java.awt.Color(108, 160, 209));
        modifyButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("MODIFY");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        modifyResetButton.setBackground(new java.awt.Color(108, 160, 209));
        modifyResetButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        modifyResetButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyResetButton.setText("RESET");
        modifyResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyFoodDialogLayout = new javax.swing.GroupLayout(modifyFoodDialog.getContentPane());
        modifyFoodDialog.getContentPane().setLayout(modifyFoodDialogLayout);
        modifyFoodDialogLayout.setHorizontalGroup(
            modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyFoodDialogLayout.createSequentialGroup()
                .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyFoodDialogLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(modifyFoodNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modifyFoodDialogLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modifyFoodLabel)
                            .addComponent(modifyDescriptionLabel)
                            .addComponent(modifyPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(modifyFoodPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(modifyFoodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(modifyFoodDialogLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(modifyResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        modifyFoodDialogLayout.setVerticalGroup(
            modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyFoodDialogLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(modifyFoodNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyFoodLabel)
                    .addComponent(modifyFoodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyDescriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyFoodPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(modifyFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyButton)
                    .addComponent(modifyResetButton))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        removeNameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        removeNameLabel.setText("Name");

        removeFoodNameComboBox.setBackground(new java.awt.Color(246, 252, 252));
        removeFoodNameComboBox.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removeFoodNameComboBox.setForeground(new java.awt.Color(45, 58, 84));
        removeFoodNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        removeFoodNameComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                removeFoodNameComboBoxFocusLost(evt);
            }
        });

        removeFoodDescriptionTextArea.setColumns(20);
        removeFoodDescriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removeFoodDescriptionTextArea.setLineWrap(true);
        removeFoodDescriptionTextArea.setRows(5);
        removeFoodDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(removeFoodDescriptionTextArea);

        removeDecriptionLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removeDecriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        removeDecriptionLabel.setText("Description");

        removeButton.setBackground(new java.awt.Color(108, 160, 209));
        removeButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeFoodDialogLayout = new javax.swing.GroupLayout(removeFoodDialog.getContentPane());
        removeFoodDialog.getContentPane().setLayout(removeFoodDialogLayout);
        removeFoodDialogLayout.setHorizontalGroup(
            removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFoodDialogLayout.createSequentialGroup()
                .addGroup(removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeFoodDialogLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(removeNameLabel)
                            .addComponent(removeDecriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(removeFoodNameComboBox, 0, 150, Short.MAX_VALUE)))
                    .addGroup(removeFoodDialogLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        removeFoodDialogLayout.setVerticalGroup(
            removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFoodDialogLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeNameLabel)
                    .addComponent(removeFoodNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(removeFoodDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeDecriptionLabel))
                .addGap(30, 30, 30)
                .addComponent(removeButton)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        foodTable.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Description", "Price"
            }
        ));
        jScrollPane1.setViewportView(foodTable);

        addFoodButton.setBackground(new java.awt.Color(108, 160, 209));
        addFoodButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        addFoodButton.setForeground(new java.awt.Color(255, 255, 255));
        addFoodButton.setText("ADD");
        addFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodButtonActionPerformed(evt);
            }
        });

        editFoodButton.setBackground(new java.awt.Color(108, 160, 209));
        editFoodButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        editFoodButton.setForeground(new java.awt.Color(255, 255, 255));
        editFoodButton.setText("EDIT");
        editFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFoodButtonActionPerformed(evt);
            }
        });

        removeFoodButton.setBackground(new java.awt.Color(108, 160, 209));
        removeFoodButton.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        removeFoodButton.setForeground(new java.awt.Color(255, 255, 255));
        removeFoodButton.setText("REMOVE");
        removeFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFoodButtonActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(255, 0, 0));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titleLabel.setText("Food");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(addFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(237, 237, 237)
                                        .addComponent(editFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(238, 238, 238)
                                        .addComponent(removeFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(658, 658, 658)
                                .addComponent(titleLabel)))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        setTheme();

        DefaultTableModel foodTableModel = (DefaultTableModel) foodTable.getModel();
        refreshFoodTable(foodTableModel);

    }//GEN-LAST:event_formWindowGainedFocus

    private void addFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodButtonActionPerformed

        FoodData foodData = new FoodData();

        addFoodDialog.setSize(800, 500);
        addNDBNoTextField.setEditable(false);
        addFoodDialog.show();

        clearAddFoodDialog();

        addNDBNoTextField.setText("" + foodData.getNewNDBNo());
        addNameTextField.requestFocus();

    }//GEN-LAST:event_addFoodButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        FoodData foodData = new FoodData();
        Food food = new Food();

        if ("".equals(addNameTextField.getText())) {

            JOptionPane.showMessageDialog(null, "Please enter name");

        } else if ("".equals(addPriceTextField.getText())) {

            JOptionPane.showMessageDialog(null, "Please enter price");

        } else {
            food.setNdbNo(Integer.parseInt(addNDBNoTextField.getText()));
            food.setName(addNameTextField.getText());
            food.setDescription(addDescriptionTextArea.getText());
            food.setPrice(Double.parseDouble(addPriceTextField.getText()));

            if (foodData.addNewFood(food)) {

                JOptionPane.showMessageDialog(null, food.getName() + " added successfully!");
                addFoodDialog.setVisible(false);

            }

        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void addNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addNameTextFieldKeyReleased

        FoodData foodData = new FoodData();

        String name = addNameTextField.getText();

        if (foodData.checkIfFoodExist(name)) {

            addNameTextField.setToolTipText("Food name already exist!");
            addButton.setEnabled(false);

        } else {

            addNameTextField.setToolTipText("");
            addButton.setEnabled(true);

        }

    }//GEN-LAST:event_addNameTextFieldKeyReleased

    private void editFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFoodButtonActionPerformed

        Sort sort = new Sort();

        DefaultComboBoxModel nameComboBoxModel = (DefaultComboBoxModel) modifyFoodNameCombo.getModel();

        modifyFoodDialog.setSize(800, 600);
        modifyFoodDialog.show();

        refreshFoodNameCombo(nameComboBoxModel);
        sort.sortComboBox(nameComboBoxModel);
        clearModifyDialog();

    }//GEN-LAST:event_editFoodButtonActionPerformed

    private void modifyFoodNameComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modifyFoodNameComboFocusLost

        FoodData foodData = new FoodData();
        Food food;

        String name = modifyFoodNameCombo.getSelectedItem().toString();

        food = foodData.getFoodDetails(name);

        modifyFoodNameTextField.setText(food.getName());
        modifyFoodDescriptionTextArea.setText(food.getDescription());
        modifyFoodPriceTextField.setText("" + food.getPrice());

    }//GEN-LAST:event_modifyFoodNameComboFocusLost

    private void modifyFoodNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modifyFoodNameTextFieldKeyReleased

        FoodData foodData = new FoodData();

        String name = modifyFoodNameTextField.getText();

        if (foodData.checkIfFoodExist(name)) {

            modifyFoodNameTextField.setToolTipText("Food name already exist!");
            modifyButton.setEnabled(false);

        } else {

            modifyFoodNameTextField.setToolTipText("");
            modifyButton.setEnabled(true);

        }

    }//GEN-LAST:event_modifyFoodNameTextFieldKeyReleased

    private void modifyResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyResetButtonActionPerformed

        FoodData foodData = new FoodData();
        Food food;

        String name = modifyFoodNameCombo.getSelectedItem().toString();

        food = foodData.getFoodDetails(name);

        modifyFoodNameTextField.setText(food.getName());
        modifyFoodDescriptionTextArea.setText(food.getDescription());
        modifyFoodPriceTextField.setText("" + food.getPrice());

    }//GEN-LAST:event_modifyResetButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed

        FoodData foodData = new FoodData();
        Food food = new Food();

        String foodName;

        foodName = modifyFoodNameCombo.getSelectedItem().toString();
        food.setName(modifyFoodNameTextField.getText());
        food.setDescription(modifyFoodDescriptionTextArea.getText());
        food.setPrice(Double.parseDouble(modifyFoodPriceTextField.getText()));

        if (foodData.modifyFood(food, foodName)) {

            JOptionPane.showMessageDialog(null, foodName + " modified successfully!");
            modifyFoodDialog.setVisible(false);

        }

    }//GEN-LAST:event_modifyButtonActionPerformed

    private void removeFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFoodButtonActionPerformed

        Sort sort = new Sort();

        DefaultComboBoxModel foodNameComboBoxModel = (DefaultComboBoxModel) removeFoodNameComboBox.getModel();

        removeFoodDialog.setSize(800, 600);
        removeFoodDialog.show();

        refreshFoodNameCombo(foodNameComboBoxModel);
        sort.sortComboBox(foodNameComboBoxModel);

    }//GEN-LAST:event_removeFoodButtonActionPerformed

    private void removeFoodNameComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_removeFoodNameComboBoxFocusLost

        FoodData foodData = new FoodData();
        Food food;

        String name = removeFoodNameComboBox.getSelectedItem().toString();
        food = foodData.getFoodDetails(name);

        removeFoodDescriptionTextArea.setText(food.getDescription());

    }//GEN-LAST:event_removeFoodNameComboBoxFocusLost

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

        FoodData foodData = new FoodData();

        int confirm;
        String name = removeFoodNameComboBox.getSelectedItem().toString();

        confirm = JOptionPane.showConfirmDialog(null, "Are you sure to remove " + name);

        if (confirm == 0) {
            if (foodData.removeFood(name)) {

                JOptionPane.showMessageDialog(null, name + " removed successfully!");
                removeFoodDialog.setVisible(false);

            }
        }

    }//GEN-LAST:event_removeButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        this.setVisible(false);
        new FoodnBeverageMenu().show();

    }//GEN-LAST:event_closeButtonActionPerformed

    private void addDescriptionTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addDescriptionTextAreaKeyReleased

        String string;

        string = addDescriptionTextArea.getText();

        if (string.length() > 100) {

            string = string.substring(0, string.length() - 1);
            addDescriptionTextArea.setText(string);

        }

    }//GEN-LAST:event_addDescriptionTextAreaKeyReleased

    private void modifyFoodDescriptionTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modifyFoodDescriptionTextAreaKeyReleased

        String string;

        string = modifyFoodDescriptionTextArea.getText();

        if (string.length() > 100) {

            string = string.substring(0, string.length() - 1);
            modifyFoodDescriptionTextArea.setText(string);

        }

    }//GEN-LAST:event_modifyFoodDescriptionTextAreaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addDescriptionLabel;
    private javax.swing.JTextArea addDescriptionTextArea;
    private javax.swing.JButton addFoodButton;
    private javax.swing.JDialog addFoodDialog;
    private javax.swing.JLabel addNDBLabel;
    private javax.swing.JTextField addNDBNoTextField;
    private javax.swing.JLabel addNameLabel;
    private javax.swing.JTextField addNameTextField;
    private javax.swing.JLabel addPriceLabel;
    private javax.swing.JTextField addPriceTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton editFoodButton;
    private javax.swing.JTable foodTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel modifyDescriptionLabel;
    private javax.swing.JTextArea modifyFoodDescriptionTextArea;
    private javax.swing.JDialog modifyFoodDialog;
    private javax.swing.JLabel modifyFoodLabel;
    private javax.swing.JComboBox<String> modifyFoodNameCombo;
    private javax.swing.JTextField modifyFoodNameTextField;
    private javax.swing.JTextField modifyFoodPriceTextField;
    private javax.swing.JLabel modifyPriceLabel;
    private javax.swing.JButton modifyResetButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel removeDecriptionLabel;
    private javax.swing.JButton removeFoodButton;
    private javax.swing.JTextArea removeFoodDescriptionTextArea;
    private javax.swing.JDialog removeFoodDialog;
    private javax.swing.JComboBox<String> removeFoodNameComboBox;
    private javax.swing.JLabel removeNameLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
