/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.GuestRegister;
import DTO.GuestRegisterData;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thehackermonk
 */
public class GuestReport extends javax.swing.JFrame {

    /**
     * Creates new form GuestReport
     */
    public GuestReport() {
        initComponents();
    }

    /**
     * Clear all text fields and table
     *
     * @param tableModel
     */
    public void clear(DefaultTableModel tableModel) {

        nameTextField.setText("");
        clearTable(tableModel);

    }

    /**
     * Clear table
     *
     * @param tableModel
     */
    public void clearTable(DefaultTableModel tableModel) {

        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }

    }

    /**
     * Get all the guest details to table
     *
     * @param tableModel
     */
    public void refreshGuestTable(DefaultTableModel tableModel) {

        GuestRegisterData guestRegisterData = new GuestRegisterData();

        ArrayList<GuestRegister> guestRegisterList = guestRegisterData.getAllGuestDetails();
        Iterator<GuestRegister> guestRegisterListIterator = guestRegisterList.iterator();

        while (guestRegisterListIterator.hasNext()) {

            GuestRegister guestRegister = guestRegisterListIterator.next();

            guestRegister.setAddress(guestRegister.getAddress().replace("\n", ", "));

            tableModel.addRow(new Object[]{guestRegister.getName(), guestRegister.getAddress(), guestRegister.getTelephoneNo(), guestRegister.getRoomNo(), guestRegister.getCheckInDate(), guestRegister.getCheckOutDate()});

        }

    }

    /**
     * Get all the guest details to table when a name is entered
     *
     * @param tableModel
     * @param name
     */
    public void refreshGuestTable(DefaultTableModel tableModel, String name) {

        GuestRegisterData guestRegisterData = new GuestRegisterData();

        ArrayList<GuestRegister> guestRegisterList = guestRegisterData.searchGuestDetails(name);
        Iterator<GuestRegister> guestRegisterListIterator = guestRegisterList.iterator();

        while (guestRegisterListIterator.hasNext()) {

            GuestRegister guestRegister = guestRegisterListIterator.next();

            guestRegister.setAddress(guestRegister.getAddress().replace("\n", ", "));

            tableModel.addRow(new Object[]{guestRegister.getName(), guestRegister.getAddress(), guestRegister.getTelephoneNo(), guestRegister.getRoomNo(), guestRegister.getCheckInDate(), guestRegister.getCheckOutDate()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        guestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        guestTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        guestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Contact", "Room No", "From", "To"
            }
        ));
        jScrollPane1.setViewportView(guestTable);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Search by Name");

        nameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameTextField.setText("jTextField1");
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTextField))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        DefaultTableModel guestTableModel = (DefaultTableModel) guestTable.getModel();

        clear(guestTableModel);
        refreshGuestTable(guestTableModel);
        nameTextField.requestFocus();

    }//GEN-LAST:event_formWindowGainedFocus

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased

        DefaultTableModel guestTableModel = (DefaultTableModel) guestTable.getModel();

        String name = nameTextField.getText();

        clearTable(guestTableModel);

        if (name.equals("")) {
            refreshGuestTable(guestTableModel); // when a name is not entered show all the guest details
        } else {
            refreshGuestTable(guestTableModel, name);
        }

    }//GEN-LAST:event_nameTextFieldKeyReleased

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.setVisible(false);
        new ReportsMenu().show();
        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTable guestTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
