/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.RestaurantType;
import DTO.RestaurantTypeData;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thehackermonk
 */
public class RestaurantTypeForm extends javax.swing.JFrame {

    /**
     * Creates new form ResturantTypeForm
     */
    public RestaurantTypeForm() {
        initComponents();
    }

    /**
     * Clear contents of the add restaurant type dialog
     */
    public void clearAddDialog() {

        addRestaurantTypeTextField.setText("");
        addDescriptionTextArea.setText("");

    }

    /**
     * To refresh contents of the restaurant type table
     */
    public void refreshRestaurantTypeTable() {

        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        DefaultTableModel restaurantTypeTableModel = (DefaultTableModel) restaurantTypeTable.getModel();

        ArrayList<RestaurantType> restaurantTypeList = restaurantTypeData.getAllRestauarantTypes();
        Iterator<RestaurantType> restaurantTypeListIterator = restaurantTypeList.iterator();

        while (restaurantTypeTableModel.getRowCount() > 0) {
            restaurantTypeTableModel.removeRow(0);
        }

        while (restaurantTypeListIterator.hasNext()) {

            RestaurantType restaurantType = restaurantTypeListIterator.next();

            restaurantTypeTableModel.addRow(new Object[]{restaurantType.getType(), restaurantType.getDescription()});

        }

    }

    /**
     * To refresh contents of the restaurant type combo box
     * 
     * @param comboBox 
     */
    public void refreshRestaurantTypeComboBox(DefaultComboBoxModel comboBox) {

        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        ArrayList<RestaurantType> restaurantTypeList = restaurantTypeData.getAllRestauarantTypes();
        Iterator<RestaurantType> restaurantTypeListIterator = restaurantTypeList.iterator();

        comboBox.removeAllElements();

        while (restaurantTypeListIterator.hasNext()) {

            RestaurantType restaurantType = restaurantTypeListIterator.next();
            comboBox.addElement(restaurantType.getType());

        }

    }

    /**
     * To check if the restaurant type is available
     * Restaurant type should be unique
     * 
     * @param type: type of restaurant
     * @return 
     */
    public boolean restaurantTypeIsAvailable(String type) {

        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        boolean isAvailable = true;

        ArrayList<RestaurantType> restaurantTypeList = restaurantTypeData.getAllRestauarantTypes();
        Iterator<RestaurantType> restaurantTypeListIterator = restaurantTypeList.iterator();

        while (restaurantTypeListIterator.hasNext()) {

            RestaurantType restaurantType = restaurantTypeListIterator.next();

            if (restaurantType.getType().equalsIgnoreCase(type)) {

                isAvailable = false;
                break;

            }

        }

        return isAvailable;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTypeDialog = new javax.swing.JDialog();
        addRestaurantTypeTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addDescriptionTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeTypeDialog = new javax.swing.JDialog();
        removeRestaurantTypeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        removeDescriptionTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        restaurantTypeTable = new javax.swing.JTable();
        addTypeButton = new javax.swing.JButton();
        removeTypeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        addRestaurantTypeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addRestaurantTypeTextField.setText("jTextField1");
        addRestaurantTypeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addRestaurantTypeTextFieldKeyReleased(evt);
            }
        });

        addDescriptionTextArea.setColumns(20);
        addDescriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addDescriptionTextArea.setLineWrap(true);
        addDescriptionTextArea.setRows(5);
        addDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(addDescriptionTextArea);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Restaurant Type");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Description");

        addButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTypeDialogLayout = new javax.swing.GroupLayout(addTypeDialog.getContentPane());
        addTypeDialog.getContentPane().setLayout(addTypeDialogLayout);
        addTypeDialogLayout.setHorizontalGroup(
            addTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTypeDialogLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(addTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRestaurantTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(299, 299, 299))
            .addGroup(addTypeDialogLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addTypeDialogLayout.setVerticalGroup(
            addTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTypeDialogLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(addTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRestaurantTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(addTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(addButton)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        removeRestaurantTypeComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeRestaurantTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        removeRestaurantTypeComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                removeRestaurantTypeComboBoxFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Restaurant Type");

        removeDescriptionTextArea.setColumns(20);
        removeDescriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeDescriptionTextArea.setLineWrap(true);
        removeDescriptionTextArea.setRows(5);
        removeDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(removeDescriptionTextArea);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Description");

        removeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeTypeDialogLayout = new javax.swing.GroupLayout(removeTypeDialog.getContentPane());
        removeTypeDialog.getContentPane().setLayout(removeTypeDialogLayout);
        removeTypeDialogLayout.setHorizontalGroup(
            removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeTypeDialogLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addGroup(removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeTypeDialogLayout.createSequentialGroup()
                        .addGroup(removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(removeRestaurantTypeComboBox, 0, 150, Short.MAX_VALUE))
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeTypeDialogLayout.createSequentialGroup()
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))))
        );
        removeTypeDialogLayout.setVerticalGroup(
            removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeTypeDialogLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeRestaurantTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(removeTypeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        restaurantTypeTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        restaurantTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Description"
            }
        ));
        jScrollPane1.setViewportView(restaurantTypeTable);

        addTypeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addTypeButton.setText("ADD");
        addTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTypeButtonActionPerformed(evt);
            }
        });

        removeTypeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeTypeButton.setText("REMOVE");
        removeTypeButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                removeTypeButtonFocusGained(evt);
            }
        });
        removeTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTypeButtonActionPerformed(evt);
            }
        });

        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(addTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(removeTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        refreshRestaurantTypeTable();

    }//GEN-LAST:event_formWindowGainedFocus

    private void addTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTypeButtonActionPerformed

        addTypeDialog.setSize(800, 525);
        addTypeDialog.show();
        clearAddDialog();
        addRestaurantTypeTextField.requestFocus();

    }//GEN-LAST:event_addTypeButtonActionPerformed

    private void addRestaurantTypeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addRestaurantTypeTextFieldKeyReleased

        String restaurantType = addRestaurantTypeTextField.getText();

        if (restaurantTypeIsAvailable(restaurantType)) {

            addRestaurantTypeTextField.setToolTipText("");
            addButton.setEnabled(true);

        } else {

            addRestaurantTypeTextField.setToolTipText("Restaurant Type already exist!");
            addButton.setEnabled(false);

        }

    }//GEN-LAST:event_addRestaurantTypeTextFieldKeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        RestaurantType restaurantType = new RestaurantType();
        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        restaurantType.setType(addRestaurantTypeTextField.getText());
        restaurantType.setDescription(addDescriptionTextArea.getText());

        if (restaurantTypeData.addRestaurantType(restaurantType)) {

            JOptionPane.showMessageDialog(null, "Restaurant type added successfully!");
            addTypeDialog.setVisible(false);

        } else {

            JOptionPane.showMessageDialog(null, "Addition of Restaurant type failed");
            clearAddDialog();
            addRestaurantTypeTextField.requestFocus();

        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void removeTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTypeButtonActionPerformed

        removeTypeDialog.setSize(800, 525);
        removeTypeDialog.show();
        
    }//GEN-LAST:event_removeTypeButtonActionPerformed

    private void removeRestaurantTypeComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_removeRestaurantTypeComboBoxFocusLost

        RestaurantType restaurantType;
        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        String type = removeRestaurantTypeComboBox.getSelectedItem().toString();

        restaurantType = restaurantTypeData.getRestaurantTypeDetails(type);

        removeDescriptionTextArea.setText(restaurantType.getDescription());

    }//GEN-LAST:event_removeRestaurantTypeComboBoxFocusLost

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        String type = removeRestaurantTypeComboBox.getSelectedItem().toString();

        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + type);

        if (confirm == 0) {

            if (restaurantTypeData.removeRestaurantType(type)) {

                JOptionPane.showMessageDialog(null, type + " removed successfully!");
                removeTypeDialog.setVisible(false);

            } else {

                JOptionPane.showMessageDialog(null, type + " unable to remove.");
                removeRestaurantTypeComboBox.requestFocus();

            }
        }

    }//GEN-LAST:event_removeButtonActionPerformed

    private void removeTypeButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_removeTypeButtonFocusGained
        
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) removeRestaurantTypeComboBox.getModel();
        refreshRestaurantTypeComboBox(comboBoxModel);
        
    }//GEN-LAST:event_removeTypeButtonFocusGained

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.setVisible(false);
        new FoodnBeverageMenu().show();
        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantTypeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea addDescriptionTextArea;
    private javax.swing.JTextField addRestaurantTypeTextField;
    private javax.swing.JButton addTypeButton;
    private javax.swing.JDialog addTypeDialog;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextArea removeDescriptionTextArea;
    private javax.swing.JComboBox<String> removeRestaurantTypeComboBox;
    private javax.swing.JButton removeTypeButton;
    private javax.swing.JDialog removeTypeDialog;
    private javax.swing.JTable restaurantTypeTable;
    // End of variables declaration//GEN-END:variables
}
