/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.Restaurant;
import Bean.RestaurantType;
import DTO.RestaurantData;
import DTO.RestaurantTypeData;
import Logic.Sort;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thehackermonk
 */
public class RestaurantForm extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantForm
     */
    public RestaurantForm() {
        initComponents();
    }

    /**
     * Clear contents of add restaurant dialog
     */
    public void clearAddDialog() {

        addNameTextField.setText("");

    }

    /**
     * To refresh contents of the restaurant table
     */
    public void refreshRestaurantTable() {

        RestaurantData restaurantData = new RestaurantData();

        DefaultTableModel tableModel = (DefaultTableModel) restaurantTable.getModel();

        ArrayList<Restaurant> restaurantList = restaurantData.getAllRestaurantDetails();
        Iterator<Restaurant> restaurantListIterator = restaurantList.iterator();

        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }

        while (restaurantListIterator.hasNext()) {

            Restaurant restaurant = restaurantListIterator.next();

            tableModel.addRow(new Object[]{restaurant.getName(), restaurant.getType()});

        }

    }

    /**
     * To refresh the contents of restaurant name combo box
     * 
     * @param comboBox 
     */
    public void refreshRestaurantNameComboBox(DefaultComboBoxModel comboBox) {

        RestaurantData restaurantData = new RestaurantData();

        ArrayList<Restaurant> restaurantList = restaurantData.getAllRestaurantDetails();
        Iterator<Restaurant> restaurantListIterator = restaurantList.iterator();

        comboBox.removeAllElements();

        while (restaurantListIterator.hasNext()) {

            Restaurant restaurant = restaurantListIterator.next();

            comboBox.addElement(restaurant.getName());

        }

    }

    /**
     * To refresh contents of restaurant type combo box
     * 
     * @param comboBox 
     */
    public void refreshRestaurantTypeComboBox(DefaultComboBoxModel comboBox) {

        RestaurantTypeData restaurantTypeData = new RestaurantTypeData();

        ArrayList<RestaurantType> restaurantTypeList = restaurantTypeData.getAllRestauarantTypes();
        Iterator<RestaurantType> restaurantTypeListIterator = restaurantTypeList.iterator();

        comboBox.removeAllElements();

        while (restaurantTypeListIterator.hasNext()) {

            RestaurantType restaurantType = restaurantTypeListIterator.next();

            comboBox.addElement(restaurantType.getType());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRestaurantDialog = new javax.swing.JDialog();
        addNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addTypeComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        addRestaurantButton = new javax.swing.JButton();
        modifyRestaurantDialog = new javax.swing.JDialog();
        modifyRestaurantNameComboBox = new javax.swing.JComboBox<>();
        modifyRestaurantNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modifyRestaurantTypeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        modifyRestaurantButton = new javax.swing.JButton();
        assignFoodRestaurantDialog = new javax.swing.JDialog();
        removeRestaurantDialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        removeRestaurantNameComboBox = new javax.swing.JComboBox<>();
        removeRestaurantTypeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        removeRestaurantButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        restaurantTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        assignFood = new javax.swing.JButton();
        removeFood = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        restaurantTypeButton = new javax.swing.JButton();

        addNameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addNameTextField.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Name");

        addTypeComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Type");

        addRestaurantButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addRestaurantButton.setText("ADD");
        addRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRestaurantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRestaurantDialogLayout = new javax.swing.GroupLayout(addRestaurantDialog.getContentPane());
        addRestaurantDialog.getContentPane().setLayout(addRestaurantDialogLayout);
        addRestaurantDialogLayout.setHorizontalGroup(
            addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRestaurantDialogLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRestaurantDialogLayout.createSequentialGroup()
                        .addGroup(addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addRestaurantDialogLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(addRestaurantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        addRestaurantDialogLayout.setVerticalGroup(
            addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRestaurantDialogLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(addRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(addRestaurantButton)
                .addGap(177, 177, 177))
        );

        modifyRestaurantNameComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modifyRestaurantNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modifyRestaurantNameComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modifyRestaurantNameComboBoxFocusLost(evt);
            }
        });

        modifyRestaurantNameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modifyRestaurantNameTextField.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Name");

        modifyRestaurantTypeComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modifyRestaurantTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Type");

        modifyRestaurantButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modifyRestaurantButton.setText("Modify Restaurant");
        modifyRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyRestaurantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyRestaurantDialogLayout = new javax.swing.GroupLayout(modifyRestaurantDialog.getContentPane());
        modifyRestaurantDialog.getContentPane().setLayout(modifyRestaurantDialogLayout);
        modifyRestaurantDialogLayout.setHorizontalGroup(
            modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyRestaurantDialogLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyRestaurantDialogLayout.createSequentialGroup()
                        .addGroup(modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modifyRestaurantNameTextField)
                            .addComponent(modifyRestaurantTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRestaurantDialogLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRestaurantDialogLayout.createSequentialGroup()
                                .addComponent(modifyRestaurantNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRestaurantDialogLayout.createSequentialGroup()
                                .addComponent(modifyRestaurantButton)
                                .addGap(30, 30, 30)))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        modifyRestaurantDialogLayout.setVerticalGroup(
            modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyRestaurantDialogLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(modifyRestaurantNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyRestaurantNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(modifyRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyRestaurantTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addComponent(modifyRestaurantButton)
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout assignFoodRestaurantDialogLayout = new javax.swing.GroupLayout(assignFoodRestaurantDialog.getContentPane());
        assignFoodRestaurantDialog.getContentPane().setLayout(assignFoodRestaurantDialogLayout);
        assignFoodRestaurantDialogLayout.setHorizontalGroup(
            assignFoodRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        assignFoodRestaurantDialogLayout.setVerticalGroup(
            assignFoodRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Name");

        removeRestaurantNameComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeRestaurantNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        removeRestaurantNameComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                removeRestaurantNameComboBoxFocusLost(evt);
            }
        });

        removeRestaurantTypeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeRestaurantTypeTextField.setText("jTextField1");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Type");

        removeRestaurantButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeRestaurantButton.setText("REMOVE");
        removeRestaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRestaurantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeRestaurantDialogLayout = new javax.swing.GroupLayout(removeRestaurantDialog.getContentPane());
        removeRestaurantDialog.getContentPane().setLayout(removeRestaurantDialogLayout);
        removeRestaurantDialogLayout.setHorizontalGroup(
            removeRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeRestaurantDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(removeRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(removeRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeRestaurantTypeTextField)
                    .addComponent(removeRestaurantNameComboBox, 0, 130, Short.MAX_VALUE))
                .addGap(307, 307, 307))
            .addGroup(removeRestaurantDialogLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(removeRestaurantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        removeRestaurantDialogLayout.setVerticalGroup(
            removeRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeRestaurantDialogLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(removeRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(removeRestaurantNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(removeRestaurantDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeRestaurantTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addComponent(removeRestaurantButton)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        restaurantTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        restaurantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Type"
            }
        ));
        jScrollPane1.setViewportView(restaurantTable);

        addButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        modifyButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        modifyButton.setText("MODIFY");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        assignFood.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        assignFood.setText("ASSIGN FOOD");
        assignFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignFoodActionPerformed(evt);
            }
        });

        removeFood.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeFood.setText("REMOVE");
        removeFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFoodActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        closeButton.setText("X");

        restaurantTypeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        restaurantTypeButton.setText("RESTAURANT TYPE");
        restaurantTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantTypeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(assignFood, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(restaurantTypeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeFood, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignFood, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFood, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        refreshRestaurantTable();

    }//GEN-LAST:event_formWindowGainedFocus

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) addTypeComboBox.getModel();

        addRestaurantDialog.setSize(800, 500);
        addRestaurantDialog.show();

        clearAddDialog();
        refreshRestaurantTypeComboBox(comboBoxModel);
        addNameTextField.requestFocus();

    }//GEN-LAST:event_addButtonActionPerformed

    private void addRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRestaurantButtonActionPerformed

        Restaurant restaurant = new Restaurant();
        RestaurantData restaurantData = new RestaurantData();

        restaurant.setName(addNameTextField.getText());
        restaurant.setType(addTypeComboBox.getSelectedItem().toString());

        if (restaurantData.addNewRestaurant(restaurant)) {

            JOptionPane.showMessageDialog(null, "Restaurant " + restaurant.getName() + " added successfully!");
            addRestaurantDialog.setVisible(false);

        } else {

            JOptionPane.showMessageDialog(null, "Addition of restaurant failed!");

        }

    }//GEN-LAST:event_addRestaurantButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed

        Sort sort = new Sort();

        DefaultComboBoxModel nameComboBoxModel = (DefaultComboBoxModel) modifyRestaurantNameComboBox.getModel();
        DefaultComboBoxModel typeComboBoxModel = (DefaultComboBoxModel) modifyRestaurantTypeComboBox.getModel();

        modifyRestaurantDialog.setSize(800, 500);
        modifyRestaurantDialog.show();

        refreshRestaurantNameComboBox(nameComboBoxModel);

        sort.sortComboBox(nameComboBoxModel);

        modifyRestaurantNameTextField.setText("");
        refreshRestaurantTypeComboBox(typeComboBoxModel);

    }//GEN-LAST:event_modifyButtonActionPerformed

    private void modifyRestaurantNameComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modifyRestaurantNameComboBoxFocusLost

        Restaurant restaurant;
        RestaurantData restaurantData = new RestaurantData();

        String restaurantName = modifyRestaurantNameComboBox.getSelectedItem().toString();

        restaurant = restaurantData.getRestaurantDetails(restaurantName);

        modifyRestaurantNameTextField.setText(restaurant.getName());
        modifyRestaurantTypeComboBox.setSelectedItem(restaurant.getType());

    }//GEN-LAST:event_modifyRestaurantNameComboBoxFocusLost

    private void modifyRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyRestaurantButtonActionPerformed

        Restaurant restaurant = new Restaurant();
        RestaurantData restaurantData = new RestaurantData();

        String name = modifyRestaurantNameComboBox.getSelectedItem().toString();
        restaurant.setName(modifyRestaurantNameTextField.getText());
        restaurant.setType(modifyRestaurantTypeComboBox.getSelectedItem().toString());

        if (restaurantData.modifyRestaurant(restaurant, name)) {

            JOptionPane.showMessageDialog(null, name + " modified successfully!");
            modifyRestaurantDialog.setVisible(false);

        } else {

            modifyRestaurantNameTextField.setText("");
            modifyRestaurantNameComboBox.requestFocus();

        }

    }//GEN-LAST:event_modifyRestaurantButtonActionPerformed

    private void assignFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignFoodActionPerformed
        
        new AssignFoodForm().setVisible(true);
        
    }//GEN-LAST:event_assignFoodActionPerformed

    private void restaurantTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantTypeButtonActionPerformed

        new ResturantTypeForm().setVisible(true);

    }//GEN-LAST:event_restaurantTypeButtonActionPerformed

    private void removeFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFoodActionPerformed

        Sort sort = new Sort();

        DefaultComboBoxModel restaurantNameComboBoxModel = (DefaultComboBoxModel) removeRestaurantNameComboBox.getModel();

        removeRestaurantDialog.show();
        removeRestaurantDialog.setSize(800, 500);

        refreshRestaurantNameComboBox(restaurantNameComboBoxModel);
        sort.sortComboBox(restaurantNameComboBoxModel);
        removeRestaurantTypeTextField.setText("");
        removeRestaurantTypeTextField.setEditable(false);

    }//GEN-LAST:event_removeFoodActionPerformed

    private void removeRestaurantNameComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_removeRestaurantNameComboBoxFocusLost

        Restaurant restaurant;
        RestaurantData restaurantData = new RestaurantData();

        String name = removeRestaurantNameComboBox.getSelectedItem().toString();
        restaurant = restaurantData.getRestaurantDetails(name);

        removeRestaurantTypeTextField.setText(restaurant.getType());

    }//GEN-LAST:event_removeRestaurantNameComboBoxFocusLost

    private void removeRestaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRestaurantButtonActionPerformed

        RestaurantData restaurantData = new RestaurantData();

        String name = removeRestaurantNameComboBox.getSelectedItem().toString();

        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + name);

        if (confirm == 0) {

            if (restaurantData.removeRestaurant(name)) {

                JOptionPane.showMessageDialog(null, name + " removed successfully!");
                removeRestaurantDialog.setVisible(false);

            } else {

                JOptionPane.showMessageDialog(null, name + " unable to remove.");
                removeRestaurantNameComboBox.requestFocus();

            }

        }

    }//GEN-LAST:event_removeRestaurantButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addNameTextField;
    private javax.swing.JButton addRestaurantButton;
    private javax.swing.JDialog addRestaurantDialog;
    private javax.swing.JComboBox<String> addTypeComboBox;
    private javax.swing.JButton assignFood;
    private javax.swing.JDialog assignFoodRestaurantDialog;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton modifyRestaurantButton;
    private javax.swing.JDialog modifyRestaurantDialog;
    private javax.swing.JComboBox<String> modifyRestaurantNameComboBox;
    private javax.swing.JTextField modifyRestaurantNameTextField;
    private javax.swing.JComboBox<String> modifyRestaurantTypeComboBox;
    private javax.swing.JButton removeFood;
    private javax.swing.JButton removeRestaurantButton;
    private javax.swing.JDialog removeRestaurantDialog;
    private javax.swing.JComboBox<String> removeRestaurantNameComboBox;
    private javax.swing.JTextField removeRestaurantTypeTextField;
    private javax.swing.JTable restaurantTable;
    private javax.swing.JButton restaurantTypeButton;
    // End of variables declaration//GEN-END:variables
}
