/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Bean.RoomType;
import DTO.RoomTypeData;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thehackermonk
 */
public class RoomTypeForm extends javax.swing.JFrame {

    /**
     * Creates new form RoomType
     */
    public RoomTypeForm() {
        initComponents();
    }

    /**
     * Clears text fields in add room type dialog box
     */
    public void clearAddRoomType() {

        roomTypeAddTypeTextField.setText("");
        roomTypeAddPriceTextField.setText("");

    }

    /**
     * Clears text fields in edit room type dialog box
     */
    public void clearEditRoomType() {

        roomTypeEditTypeTextField.setText("");
        roomTypeEditPriceTextField.setText("");

    }

    /**
     * Refresh the contents of RoomTypeTable
     */
    public void refreshRoomTypeTable() {

        RoomTypeData roomTypeData = new RoomTypeData();

        DefaultTableModel roomTypeTableModel = (DefaultTableModel) roomTypeTable.getModel();

        while (roomTypeTableModel.getRowCount() > 0) {

            roomTypeTableModel.removeRow(0);

        }

        ArrayList<RoomType> roomTypeList = roomTypeData.getAllRoomTypeDetails();
        Iterator<RoomType> roomTypeListIterator = roomTypeList.iterator();

        while (roomTypeListIterator.hasNext()) {

            RoomType roomType = roomTypeListIterator.next();

            roomTypeTableModel.addRow(new Object[]{roomType.getType(), roomType.getPrice()});

        }

    }

    /**
     * Refresh the contents of RoomType combo box
     *
     * @param comboBoxModel any combo box which holds the value room type
     */
    public void refreshRoomTypeComboBox(DefaultComboBoxModel comboBoxModel) {

        RoomTypeData roomTypeData = new RoomTypeData();

        comboBoxModel.removeAllElements();

        ArrayList<RoomType> roomTypeList = roomTypeData.getAllRoomTypeDetails();
        Iterator<RoomType> roomTypeListIterator = roomTypeList.iterator();

        while (roomTypeListIterator.hasNext()) {

            RoomType roomType = roomTypeListIterator.next();
            comboBoxModel.addElement(roomType.getType());

        }

    }

    /**
     * To check if the entered name for room type is valid (must be unique)
     *
     * @param type name for room type entered by the user
     * @return true if it is a valid room type, and false if it is an invalid
     * room type
     */
    public boolean isValidRoomType(String type) {

        RoomTypeData roomTypeData = new RoomTypeData();
        Boolean valid = true;

        ArrayList<RoomType> roomTypeList = roomTypeData.getAllRoomTypeDetails();
        Iterator<RoomType> roomTypeListIterator = roomTypeList.iterator();

        while (roomTypeListIterator.hasNext()) {

            RoomType roomType = roomTypeListIterator.next();

            if (type.equalsIgnoreCase(roomType.getType())) {
                valid = false;
            }

        }

        return valid;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomTypeAddDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roomTypeAddTypeTextField = new javax.swing.JTextField();
        roomTypeAddPriceTextField = new javax.swing.JTextField();
        addRoomTypeAddButton = new javax.swing.JButton();
        roomTypeEditDialog = new javax.swing.JDialog();
        roomTypeEditTypeCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        roomTypeEditTypeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roomTypeEditPriceTextField = new javax.swing.JTextField();
        editRoomTypeSaveButton = new javax.swing.JButton();
        roomTypeRemoveDialog = new javax.swing.JDialog();
        roomTypeRemoveTypeCombo = new javax.swing.JComboBox<>();
        removeRoomTypeRemoveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomTypeTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Room Type");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Price");

        roomTypeAddTypeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeAddTypeTextField.setText("jTextField1");
        roomTypeAddTypeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roomTypeAddTypeTextFieldKeyReleased(evt);
            }
        });

        roomTypeAddPriceTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeAddPriceTextField.setText("jTextField2");

        addRoomTypeAddButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addRoomTypeAddButton.setText("ADD");
        addRoomTypeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomTypeAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomTypeAddDialogLayout = new javax.swing.GroupLayout(roomTypeAddDialog.getContentPane());
        roomTypeAddDialog.getContentPane().setLayout(roomTypeAddDialogLayout);
        roomTypeAddDialogLayout.setHorizontalGroup(
            roomTypeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTypeAddDialogLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(roomTypeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roomTypeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomTypeAddTypeTextField)
                    .addComponent(roomTypeAddPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomTypeAddDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRoomTypeAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        roomTypeAddDialogLayout.setVerticalGroup(
            roomTypeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTypeAddDialogLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(roomTypeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomTypeAddTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roomTypeAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roomTypeAddPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(addRoomTypeAddButton)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        roomTypeEditTypeCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeEditTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomTypeEditTypeCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                roomTypeEditTypeComboFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Room Type");

        roomTypeEditTypeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeEditTypeTextField.setText("jTextField1");
        roomTypeEditTypeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roomTypeEditTypeTextFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Price");

        roomTypeEditPriceTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeEditPriceTextField.setText("jTextField2");

        editRoomTypeSaveButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        editRoomTypeSaveButton.setText("SAVE");
        editRoomTypeSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoomTypeSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomTypeEditDialogLayout = new javax.swing.GroupLayout(roomTypeEditDialog.getContentPane());
        roomTypeEditDialog.getContentPane().setLayout(roomTypeEditDialogLayout);
        roomTypeEditDialogLayout.setHorizontalGroup(
            roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTypeEditDialogLayout.createSequentialGroup()
                .addGroup(roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomTypeEditDialogLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editRoomTypeSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomTypeEditTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roomTypeEditDialogLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomTypeEditTypeTextField)
                            .addComponent(roomTypeEditPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        roomTypeEditDialogLayout.setVerticalGroup(
            roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTypeEditDialogLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(roomTypeEditTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roomTypeEditTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roomTypeEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roomTypeEditPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(editRoomTypeSaveButton)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        roomTypeRemoveTypeCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeRemoveTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeRoomTypeRemoveButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeRoomTypeRemoveButton.setText("REMOVE");
        removeRoomTypeRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRoomTypeRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomTypeRemoveDialogLayout = new javax.swing.GroupLayout(roomTypeRemoveDialog.getContentPane());
        roomTypeRemoveDialog.getContentPane().setLayout(roomTypeRemoveDialogLayout);
        roomTypeRemoveDialogLayout.setHorizontalGroup(
            roomTypeRemoveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomTypeRemoveDialogLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addGroup(roomTypeRemoveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomTypeRemoveTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roomTypeRemoveDialogLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(removeRoomTypeRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        roomTypeRemoveDialogLayout.setVerticalGroup(
            roomTypeRemoveDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomTypeRemoveDialogLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(roomTypeRemoveTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(removeRoomTypeRemoveButton)
                .addGap(182, 182, 182))
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        roomTypeTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roomTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Price"
            }
        ));
        jScrollPane1.setViewportView(roomTypeTable);

        addButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(152, 152, 152)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(153, 153, 153)
                            .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(313, 313, 313))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(297, 297, 297)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(removeButton))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        refreshRoomTypeTable();

    }//GEN-LAST:event_formWindowGainedFocus

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        roomTypeAddDialog.setSize(800, 500);
        clearAddRoomType();
        roomTypeAddDialog.show();

    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) roomTypeEditTypeCombo.getModel();

        refreshRoomTypeComboBox(comboBoxModel);
        clearEditRoomType();

        roomTypeEditDialog.setSize(800, 500);

        roomTypeEditDialog.show();
        roomTypeEditTypeCombo.requestFocus();

    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) roomTypeRemoveTypeCombo.getModel();

        refreshRoomTypeComboBox(comboBoxModel);

        roomTypeRemoveDialog.setSize(800, 500);
        roomTypeRemoveDialog.show();

    }//GEN-LAST:event_removeButtonActionPerformed

    private void addRoomTypeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomTypeAddButtonActionPerformed

        RoomType roomType = new RoomType();
        RoomTypeData roomTypeData = new RoomTypeData();

        roomType.setType(roomTypeAddTypeTextField.getText());
        roomType.setPrice(Float.parseFloat(roomTypeAddPriceTextField.getText()));

        if (roomTypeData.addRoomType(roomType)) {

            JOptionPane.showMessageDialog(null, "Room type added successfully");
            roomTypeAddDialog.setVisible(false);

        }

    }//GEN-LAST:event_addRoomTypeAddButtonActionPerformed

    private void roomTypeEditTypeComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomTypeEditTypeComboFocusLost

        RoomType roomType;
        RoomTypeData roomTypeData = new RoomTypeData();

        String type = roomTypeEditTypeCombo.getSelectedItem().toString();

        roomType = roomTypeData.getRoomTypeDetails(type);

        clearEditRoomType();

        roomTypeEditTypeTextField.setText(roomType.getType());
        roomTypeEditPriceTextField.setText(roomType.getPrice().toString());

    }//GEN-LAST:event_roomTypeEditTypeComboFocusLost

    private void editRoomTypeSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoomTypeSaveButtonActionPerformed

        RoomType roomType = new RoomType();
        RoomTypeData roomTypeData = new RoomTypeData();

        String type;

        type = roomTypeEditTypeCombo.getSelectedItem().toString();
        roomType.setType(roomTypeEditTypeTextField.getText());
        roomType.setPrice(Float.parseFloat(roomTypeEditPriceTextField.getText()));

        if (roomTypeData.updateRoomType(type, roomType)) {

            JOptionPane.showMessageDialog(null, type + " updated successfully!");
            roomTypeEditDialog.setVisible(false);

        }

    }//GEN-LAST:event_editRoomTypeSaveButtonActionPerformed

    private void removeRoomTypeRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRoomTypeRemoveButtonActionPerformed

        RoomTypeData roomTypeData = new RoomTypeData();

        String type;
        int confirm;

        type = roomTypeRemoveTypeCombo.getSelectedItem().toString();
        confirm = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + type);

        if (confirm == 0) {

            if (roomTypeData.removeRoomType(type)) {

                JOptionPane.showMessageDialog(null, type + " removed successfully!");
                roomTypeRemoveDialog.setVisible(false);

            }

        }

    }//GEN-LAST:event_removeRoomTypeRemoveButtonActionPerformed

    private void roomTypeAddTypeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomTypeAddTypeTextFieldKeyReleased

        String type = roomTypeAddTypeTextField.getText();

        if (!isValidRoomType(type)) {

            addRoomTypeAddButton.setEnabled(false);
            roomTypeAddTypeTextField.setToolTipText("Room type already exist!");

        } else {

            addRoomTypeAddButton.setEnabled(true);
            roomTypeAddTypeTextField.setToolTipText("");

        }

    }//GEN-LAST:event_roomTypeAddTypeTextFieldKeyReleased

    private void roomTypeEditTypeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomTypeEditTypeTextFieldKeyReleased

        String type = roomTypeEditTypeTextField.getText();

        if (!isValidRoomType(type)) {

            editRoomTypeSaveButton.setEnabled(false);
            roomTypeEditTypeTextField.setToolTipText("Room type already exist!");

        } else {

            editRoomTypeSaveButton.setEnabled(true);
            roomTypeEditTypeTextField.setToolTipText("");

        }

    }//GEN-LAST:event_roomTypeEditTypeTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomTypeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomTypeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addRoomTypeAddButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editRoomTypeSaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeRoomTypeRemoveButton;
    private javax.swing.JDialog roomTypeAddDialog;
    private javax.swing.JTextField roomTypeAddPriceTextField;
    private javax.swing.JTextField roomTypeAddTypeTextField;
    private javax.swing.JDialog roomTypeEditDialog;
    private javax.swing.JTextField roomTypeEditPriceTextField;
    private javax.swing.JComboBox<String> roomTypeEditTypeCombo;
    private javax.swing.JTextField roomTypeEditTypeTextField;
    private javax.swing.JDialog roomTypeRemoveDialog;
    private javax.swing.JComboBox<String> roomTypeRemoveTypeCombo;
    private javax.swing.JTable roomTypeTable;
    // End of variables declaration//GEN-END:variables
}
